### PR TITLE
Auth flow

### LINKED ISSUE #4: Auth flow
In order to manage network, first step is to log-in to Ucentral app where users will be able to manage their devices.
Authenticate_IPAddress
https://share.goabstract.com/c7f8eb13-f97c-43f7-9a9c-9cc7a2a0f3fe
Authenticate_Password
https://share.goabstract.com/0f36291b-4463-49c0-a18d-96dc8ec66d5a
Authenticate_ErrorHandling_FieldError
https://share.goabstract.com/801b353c-8e8f-48e9-a096-cb9c6924d6ba

Auth process is a multi-step form where users need to provide device ip address and password.
It has only a logo, header and section description text as well as inputs with labels and eventual error messages and a button to either proceed to next step or login once the multi-step process is finished.

✅  Given all data was correct and login process succeeded, two behaviours may occur.
- 🥇 Given user is setting up network for the first time, then
Then they're redirected to a "NewSetup" wizard #6 

- 👍 Given user has already existing network
Then they're redirected to a "dashboard" #5 

🛑 Given some data was incorrect
Then an input highlights and shows an error message under it.

### Notes
'Forgot password' and 'Where is my IP Address' features have been removed, and won't be implemented.

### Questions
- [ ] Does logo in header link to anywhere?
- [ ] How should the button look like in disabled state?
Screenshot 2021-05-19 at 20 42 28
- [ ] How should the button look when in pending state (e.g. while the request is being processed)?
- [ ] How do we go back to IP address screen in case both credentials are wrong, not just password?

### TODOS
- [x] setup css libriaries
tailwind - requires to be initialised with a configuration file, it can be generated with `tailwind init app/tailwind/config.js --full` command. We're passing 'full' flag because we want the whole default configuration provided.
Tailwind setup guide: https://dev.to/jamesbyrne/using-tailwindcss-with-ember-41el
- [x] Configure tailwind theme to match the designs.
- [x] ember-css-modules
We will be using ember-css-modules addon together with tailwind classes used in css rather than html.
We'll be using all linting rules provided by:
https://github.com/simplabs/ember-template-lint-plugin-css-modules
- [x] create 'auth' route
  - [x] Auth component
     If the field is empty, then we should put it in error state.
   When authentication request is rejected it should put inputs in error state and show a failure message.
- [x] Layout
  - [x] page Header component
   Should include a logo, configurable title and description.
  - [x] Button component
    - [x] Pending state
    - [x] Disabled state
    ember-concurrency(?)
  - [x] Input component
    - [x] label
    - [x] error state
    - [x] error message
  - [ ] PasswordInput component
    -  [ ] Visibility feature - need icon asset
- [x] auth service (async login() just always returns true for now)
login method returns a promise that returns a boolean when authentication succeeds or fails, but will return an error in case e.g. connection issue.

### Dependencies
depends on #1 

ember-concurrency
ember-concurrency-decorators
We'll be using all linting rules provided by:
https://github.com/simplabs/eslint-plugin-ember-concurrency

### PR DESCRIPTION
**Pull request by BobrImperator**
closes #4
Adds layout component
Basic input components

- [ ] Password visiblity not implemented
  No assets provided, the one from sketch don't seem to work outside of it - could be done separately

Screenshot 2021-05-21 at 09 25 38

Screenshot 2021-05-21 at 09 26 18

Screenshot 2021-05-21 at 09 27 19

Screenshot 2021-05-21 at 09 14 18

### CODE REVIEW

**Comment by marcoow** [comment]
@BobrImperator something doesn't seem quite right yet?

Bildschirmfoto 2021-05-21 um 09 54 23

File: app/routes/auth.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+import Route from "@ember/routing/route";
+
+export default class AuthRoute extends Route {}
```
Comment (marcoow) [inline app/routes/auth.js:3]: This can be removed

File: app/routes/dashboard.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+import Route from "@ember/routing/route";
+
+export default class DashboardRoute extends Route {}
```
Comment (marcoow) [inline app/routes/dashboard.js:3]: This can be removed

**Review by marcoow — COMMENTED** [review]
This looks good overall!

Let's add some tests for all components though, I think there's a bunch of cases for the inputs for example around error states, disabling etc…

File: app/components/auth/template.hbs [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+    {{#if this.isIpAddressStep}}
+      {{t "auth.ip_address.description"}}
+    {{/if}}
+    
+    {{#if this.isPasswordStep}}
+      {{t "auth.router_password.description"}}
+    {{/if}}
+  </:description>
+
+  <:default>
```
[the remark this answers is not in the document]
Comment (BobrImperator) [reply app/components/auth/template.hbs:22]: I believe this can be resolved once #20 hits main, and #10 is rebased.

File: app/components/auth/component.js [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+      password: this.password,
+    });
+
+    if (isAuthenticated) {
+      this.router.transitionTo("dashboard");
+    } else {
+      this.currentStep = this.STEPS.IP_ADDRESS;
+      this.loginFailedMessage = this.intl.t("auth.incorrect_credentials");
+    }
+  }
```
[the remark this answers is not in the document]
Comment (BobrImperator) [reply app/components/auth/component.js:56]: Was thinking about doing it once ESA can be used, but you're right.

[the remark this answers is not in the document]
Comment (marcoow) [reply app/components/auth/component.js:56]: I'd do it now – doesn't matter after all what happens **inside** of the task.

File: app/components/auth.js [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+
+  @tracked currentStep = this.STEPS.IP_ADDRESS;
+  @tracked ipAddress = "";
+  @tracked password = "";
+  @tracked loginFailedMessage = "";
+
+  STEPS = {
+    IP_ADDRESS: "IP_ADDRESS",
+    PASSWORD: "PASSWORD",
+  };
```
Comment (marcoow) [inline app/components/auth.js:21]: I think these could just be constants outside of the class?

```js
const STEP_IP_ADDRESS = "IP_ADDRESS";
```

or so? I think making them a property is slightly confusing… – bit of a nitpick of course so feel free to ignore 👍

File: app/components/auth.js [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+  @action
+  handleIpAddress(event) {
+    this.ipAddress = event.target.value;
+  }
+
+  @task
+  *loginTask(credentials) {
+    const useMockAuthenticator = this.config.getConfig(
+      "APP.useMockAuthenticator"
+    );
```
Comment (marcoow) [inline app/components/auth.js:70]: We should mock this in the test – see above. I wouldn't worry about production and the fact that the real API isn't present at this point.

File: app/router.js [hunk 7]
```diff
@@ -6,4 +6,7 @@ export default class Router extends EmberRouter {
   rootURL = config.rootURL;
 }
 
-Router.map(function () {});
+Router.map(function () {
+  this.route("auth");
+  this.route("logout");
```
Comment (marcoow) [inline app/router.js:11]: We shouldn't need a route for logging out. In fact I don't think we need support for logging out at all in this app.

File: app/routes/application.js [hunk 8]
```diff
@@ -3,10 +3,10 @@ import { inject as service } from "@ember/service";
 
 export default class ApplicationRoute extends Route {
   @service intl;
+  @service router;
 
-  beforeModel() {
-    super.beforeModel(...arguments);
-
+  beforeModel(transition) {
+    super.beforeModel(transition);
```
Comment (marcoow) [inline app/routes/application.js:9]: I think generally the pattern with just forwarding `...arguments` is simpler and more robust unless we actually **use** the arguments?

File: app/routes/index.js [hunk 9]
```diff
@@ -0,0 +1,10 @@
+import Route from "@ember/routing/route";
+import { inject as service } from "@ember/service";
+
+export default class IndexRoute extends Route {
+  @service session;
+
+  beforeModel() {
+    this.session.requireAuthentication(null, "auth");
```
Comment (marcoow) [inline app/routes/index.js:8]:
```suggestion
  beforeModel(transition) {
    this.session.requireAuthentication(transition, "auth");
```

`requireAuthentication` needs the transition so it can retry that once the session has been authenticated.

File: app/routes/logout.js [hunk 10]
```diff
@@ -0,0 +1,11 @@
...
+import { inject as service } from "@ember/service";
+
+export default class LogoutRoute extends Route {
+  @service session;
+
+  beforeModel() {
+    this.session.invalidate();
+    this.session.requireAuthentication(null, "auth");
+  }
+}
```
Comment (marcoow) [inline app/routes/logout.js:11]: I don't think we need this?

File: app/services/config.js [hunk 11]
```diff
@@ -0,0 +1,13 @@
...
+
+export default class ConfigService extends Service {
+  get config() {
+    return getOwner(this).resolveRegistration("config:environment");
+  }
+
+  getConfig(key) {
+    return get(this.config, key);
+  }
+}
```
Comment (marcoow) [inline app/services/config.js:13]: I'd reconsider whether we need this service. You can always access the configuration by importing it:

```js
import ENV from "ucentral/config/environment";
```

File: tests/acceptance/authentication-test.js [hunk 12]
```diff
@@ -0,0 +1,56 @@
...
+
+module("Acceptance | authentication", function (hooks) {
+  setupApplicationTest(hooks);
+  setupPretender(hooks);
+
+  test("user is redirected to /auth when not authenticated", async function (assert) {
+    this.pretender.post("/authenticate", () => {
+      assert.ok(true, "successfuly hit authenticate endpoint");
+      return [200, {}, "{}"];
+    });
```
Comment (marcoow) [inline tests/acceptance/authentication-test.js:20]: I'm not sure why this is needed in this test? The `/authenticate` endpoint should only be requested once the user submits the auth form? I'd also suggest using ESA's `invalidateSession` test helper here to set the session up as un-authenticated: https://github.com/simplabs/ember-simple-auth#testing

File: tests/acceptance/authentication-test.js [hunk 13]
```diff
@@ -0,0 +1,56 @@
...
+
+    assert.equal(currentURL(), "/auth");
+  });
+
+  test("given user entered correct credentials they are redirected to /dashboard", async function (assert) {
+    this.pretender.post("/authenticate", () => {
+      return [200, {}, "{}"];
+    });
+    const authStub = createAuthServiceStub(async () => true);
+    this.owner.register("service:auth", authStub);
```
Comment (marcoow) [inline tests/acceptance/authentication-test.js:31]: I don't think the `auth` service exists still?

File: tests/acceptance/authentication-test.js [hunk 14]
```diff
@@ -0,0 +1,56 @@
...
+    await fillIn("[data-test-ip-address] [data-test-input]", "192.168.1.2");
+    await click("[data-test-confirm-button]");
+
+    await fillIn("[data-test-password] [data-test-password-input]", "Secret");
+    await click("[data-test-confirm-button]");
+
+    assert.equal(currentURL(), "/");
+  });
+
+  test("given user entered incorrect credentials they are not redirected", async function (assert) {
```
Comment (marcoow) [inline tests/acceptance/authentication-test.js:43]: This seems to be missing a request stub with Pretender?

File: tests/acceptance/authentication-test.js [hunk 15]
```diff
@@ -0,0 +1,56 @@
...
+
+    await fillIn("[data-test-ip-address] [data-test-input]", "192.168.1.2");
+    await click("[data-test-confirm-button]");
+
+    await fillIn("[data-test-password] [data-test-password-input]", "Secret");
+    await click("[data-test-confirm-button]");
+
+    assert.equal(currentURL(), "/auth");
+  });
+});
```
Comment (marcoow) [inline tests/acceptance/authentication-test.js:56]: I'd add some tests here to assert that:

* when login fails, the flow goes back to the first step (IP input) and shows an error message
* the buttons are disabled until data is put in/while the auth request is being handled

File: tests/unit/authenticators/ucentral-router-test.js [hunk 16]
```diff
@@ -0,0 +1,73 @@
...
+    );
+  });
+
+  test("#restore returns data it received", async function (assert) {
+    assert.expect(1);
+
+    const data = await this.authenticator.restore({ succeeded: true });
+
+    assert.deepEqual(data, { succeeded: true });
+  });
```
Comment (marcoow) [inline tests/unit/authenticators/ucentral-router-test.js:72]: `restore` should also reject when passed an empty session. ESA will always try and restore a session on startup which we want to fail in case there is no valid session data.

File: app/authenticators/mock-ucentral-router.js [hunk 17]
```diff
@@ -0,0 +1,14 @@
...
+  restore(data) {
+    return new RSVP.Promise((resolve) => {
+      return resolve(data);
+    });
+  }
+
+  authenticate() {
+    return new RSVP.Promise((resolve) => resolve({ succeeded: true }));
+  }
+}
```
[the remark this answers is not in the document]
Comment (BobrImperator) [reply app/authenticators/mock-ucentral-router.js:14]: We want this mock in production as well I think because otherwise there's no way to 'log in'.

The mock is not used in tests at all, they have their own mocks.
UcentralMock is used for development and (for now) in prod to test things.

File: app/components/auth.hbs [hunk 18]
```diff
@@ -0,0 +1,67 @@
+<Uc::Layout>
+  <:title>
+    {{#if this.isIpAddressStep}}
+      {{t "auth.ip_address.title"}}
+    {{/if}}
+
+    {{#if this.isPasswordStep}}
```
[the remark this answers is not in the document]
Comment (BobrImperator) [reply app/components/auth.hbs:7]: I think it wouldn't, it also doesn't really makes sense to chain them as only one of the properties can be truthy at a time and at least 1 has to be truthy as well.

File: app/components/auth.js (hunk 6 above)
Comment (BobrImperator) [reply app/components/auth.js:70]: as mentioned above, we have no other way to develop with or use the preview.

File: app/router.js (hunk 7 above)
Comment (BobrImperator) [reply app/router.js:11]: That might be true, but it makes it easier to develop with, of course we can always inspect the service and invalidate session amnually.

File: app/authenticators/mock-ucentral-router.js (hunk 17 above)
[the remark this answers is not in the document]
Comment (marcoow) [reply app/authenticators/mock-ucentral-router.js:14]: I'd rather set up pretender mocks for this in all environments then.

File: app/components/auth.hbs (hunk 18 above)
[the remark this answers is not in the document]
Comment (marcoow) [reply app/components/auth.hbs:7]: Yes but this code makes it seem like both could be true at the same time?

File: app/router.js (hunk 7 above)
Comment (marcoow) [reply app/router.js:11]: You can also just delete the session from storage

File: app/authenticators/ucentral-router.js [hunk 19]
```diff
@@ -0,0 +1,34 @@
...
+export default class UcentralRouterAuthenticator extends Base {
+  restore(data) {
+    return new RSVP.Promise((resolve) => {
+      return resolve(data);
+    });
+  }
+
+  authenticate(credentials) {
+    return new RSVP.Promise((resolve, reject) => {
+      const authenticateRequest = fetch("/authenticate", {
```
Comment (marcoow) [inline app/authenticators/ucentral-router.js:14]: This is the actual request we'll be using btw: https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/test_scripts/curl/cli#L41

File: app/routes/application.js (hunk 8 above)
Comment (BobrImperator) [reply app/routes/application.js:9]: I believe passing arguments manually instead of spreading them makes the code clearer, and is 'typed' in a way.
It seems to me to be easier to reason about.

But I don't have that strong opinion on this, will change.

File: app/services/config.js (hunk 11 above)
Comment (BobrImperator) [reply app/services/config.js:13]: I've always found this way of config access to be weird, and a dedicated service makes it easier to track what is used.
Will change it though.

File: tests/acceptance/authentication-test.js (hunk 12 above)
Comment (BobrImperator) [reply tests/acceptance/authentication-test.js:20]: Seems to be a left over of some sort, will fix that up.

File: tests/acceptance/authentication-test.js (hunk 13 above)
Comment (BobrImperator) [reply tests/acceptance/authentication-test.js:31]: Nope it doesn't, I removed injections from code, but must've left it in tests.

File: tests/acceptance/authentication-test.js (hunk 14 above)
Comment (BobrImperator) [reply tests/acceptance/authentication-test.js:43]: Not really, but I think that could make two tests.
Right now it doesn't matter whether authenticate failed because of wrong credentials or not existing endpoint.

File: tests/acceptance/authentication-test.js (hunk 15 above)
Comment (BobrImperator) [reply tests/acceptance/authentication-test.js:56]: The first one is tested in an integration test, here we only make sure we stay on the same route.

File: app/authenticators/ucentral-router.js (hunk 19 above)
Comment (BobrImperator) [reply app/authenticators/ucentral-router.js:14]: They seem to be using oauth2 spec, do we need custom authenticator then?
Are you sure we will be using this api? They seem to be using emails/password pairs - some account credentials, but we require an IP address in the app?

Comment (marcoow) [reply app/authenticators/ucentral-router.js:14]: Yes, we should use a custom authenticator. From what I can see the only change necessary should be renaming the arguments?

Comment (BobrImperator) [reply app/authenticators/ucentral-router.js:14]: If we're going with the custom authenticator, then yes, only arguments and url would need to change.

File: app/authenticators/mock-ucentral-router.js (hunk 17 above)
[the remark this answers is not in the document]
Comment (BobrImperator) [reply app/authenticators/mock-ucentral-router.js:14]: I think we should consider ember-cli-mirage then, it already have an opinionated structure and handles starting up in other environments by leveraging initializers which is probably what we'd have to do as well if we want to run it in every environment.

[the remark this answers is not in the document]
Comment (marcoow) [reply app/authenticators/mock-ucentral-router.js:14]: ok, let's go with that 👍

File: app/components/auth.js [hunk 20]
```diff
@@ -0,0 +1,76 @@
...
+
+    this.loginTask
+      .perform({
+        userId: this.ipAddress,
+        password: this.password,
+      })
+      .catch(() => {
+        this.currentStep = STEPS.IP_ADDRESS;
+        this.loginFailedMessage = this.intl.t("auth.incorrect_credentials");
+      });
```
Comment (marcoow) [inline app/components/auth.js:56]: I'd use `try`/`catch` here – the action is `async` already anway.

File: app/components/auth.hbs [hunk 21]
```diff
@@ -0,0 +1,61 @@
...
+
+        <Uc::Button
+          @onClick={{this.confirmIpAddress}}
+          local-class="auth__confirm-button"
+          disabled={{this.isIpAddressConfirmDisabled}}
+          data-test-confirm-button
+          {{on "click" this.confirmIpAddress}}
+        >
+          {{t "actions.next"}}
+        </Uc::Button>
```
Comment (marcoow) [inline app/components/auth.hbs:39]: I'd wrap this in a `<form>` as well so you can hit return in the text field to submit.

File: tests/integration/components/auth/component-test.js [hunk 22]
```diff
@@ -0,0 +1,100 @@
...
+    assert.dom("[data-test-confirm-button]").hasAttribute("disabled");
+  });
+
+  test("'login' button is disabled when authentication request is in progress", async function (assert) {
+    assert.expect(2);
+    const authStub = createAuthServiceStub(
+      () =>
+        new Promise((resolve) => {
+          setTimeout(resolve, 300);
+        })
```
Comment (marcoow) [inline tests/integration/components/auth/component-test.js:84]: This approach makes the test time-dependent and potentially slow. You can use this pattern instead:

```js
click("[data-test-confirm-button]"); // no await
waitFor(`[data-test-confirm-button].${confirmButtonStyles["--loading"]}`);
await settled();
```

File: tests/unit/authenticators/ucentral-router-test.js [hunk 23]
```diff
@@ -0,0 +1,92 @@
...
+import UcentralRouterAuthenticator from "ucentral/authenticators/ucentral-router";
+import { setupTest } from "ember-qunit";
+import { Response } from "miragejs";
+
+module("Unit | Authenticator | UcentralRouterAuthenticator", function (hooks) {
+  setupTest(hooks);
+  setupMirage(hooks);
+
+  hooks.beforeEach(function () {
+    this.authenticator = UcentralRouterAuthenticator.create();
```
Comment (marcoow) [inline tests/unit/authenticators/ucentral-router-test.js:12]:
```suggestion
    this.authenticator = this.owner.lookup("authenticator:ucentral-router");
```

Instances of anything should always be resolved via the container.

File: app/components/auth.js (hunk 20 above)
Comment (BobrImperator) [reply app/components/auth.js:56]: Do you mean something like this?

```
    try {
      await this.loginTask.perform({
        userId: this.ipAddress,
        password: this.password,
      });
    } catch (error) {
      this.currentStep = STEPS.IP_ADDRESS;
      this.loginFailedMessage = this.intl.t("auth.incorrect_credentials");
    }

```
  In case the task is cancelled the `.catch` will be cancelled as well, which isn't true for `try catch` version

Comment (marcoow) [reply app/components/auth.js:56]: Yes, that's what I meant. Are you sure about `catch`? Isn't that just the `catch` method on `Promise`?

Comment (marcoow) [reply app/components/auth.js:56]: When you change to `try`/`catch` you also need to `await` the `perform`. Can you check that still breaks the test? Otherwise that's something we should change in https://github.com/simplabs/eslint-plugin-ember-concurrency/blob/master/rules/no-perform-without-catch.md maybe…

File: tests/integration/components/auth/component-test.js (hunk 22 above)
Comment (BobrImperator) [reply tests/integration/components/auth/component-test.js:84]: It's as time-dependent as waitFor is, plus its more complicated setup.

The return value of stubbed function is used in a task, so it's not waiting any longer than it must since it's concurrent, as soon as the test button is clicked and fires the stub, it can complete.

File: app/components/auth.hbs (hunk 21 above)
Comment (BobrImperator) [reply app/components/auth.hbs:39]: Thanks for pointing that out, I meant to put the whole thing in form actually.

File: tests/integration/components/auth/component-test.js (hunk 22 above)
Comment (marcoow) [reply tests/integration/components/auth/component-test.js:84]: I'm not sure I understand tbh. Isn't the 300ms delay here so it would sleep just long enough so that the assertions can run before (and it works because `await click("[data-test-confirm-button]");` doesn't actually await the completion of the request)? I wouldn't recommend that pattern as its potentially brittle – also see [this conversation on our Slack](https://simplabs.slack.com/archives/C55DR890R/p1613664556026000) from a few weeks ago.

File: app/components/auth.js (hunk 20 above)
Comment (BobrImperator) [reply app/components/auth.js:56]: This is the exact code that I tried 

```
    try {
      await this.loginTask.perform({
        userId: this.ipAddress,
        password: this.password,
      });
    } catch (error) {
      this.currentStep = STEPS.IP_ADDRESS;
      this.loginFailedMessage = this.intl.t("auth.incorrect_credentials");
    }
    ```
    And it's probably a good idea to change the rule for error handling

File: tests/integration/components/auth/component-test.js (hunk 22 above)
Comment (BobrImperator) [reply tests/integration/components/auth/component-test.js:84]: No, the delay is only to put thing in 'pending' state, it doesn't await it, the delay could be 5s long and it'd still pass in 100ms. I need to return a delayed promise here, otherwise it will be immediately resolved and won't be able to test the loading state.

What you linked seems to be a slightly different case, especially that for some reason you needed to use `click` without awaiting it which was the source of the issue.

File: app/authenticators/ucentral-router.js [hunk 24]
```diff
@@ -0,0 +1,28 @@
+import Base from "ember-simple-auth/authenticators/base";
+import fetch from "fetch";
+import RSVP from "rsvp";
+
+export default class UcentralRouterAuthenticator extends Base {
+  restore(data) {
+    return new RSVP.Promise((resolve, reject) => {
+      if (!data || !Object.keys(data).length) {
+        return reject("UcentralRouterAuthenticator was provided empty session");
```
Comment (Turbo87) [inline app/authenticators/ucentral-router.js:9]: Promises should always be rejected with `Error` instances or subclasses of it

File: app/authenticators/ucentral-router.js [hunk 25]
```diff
@@ -0,0 +1,28 @@
...
+      }
+      return resolve(data);
+    });
+  }
```
Comment (Turbo87) [inline app/authenticators/ucentral-router.js:13]:
```suggestion
  async restore(data) {
      if (!data || !Object.keys(data).length) {
        throw new Error("UcentralRouterAuthenticator was provided empty session");
      }
      return data;
    });
  }
```

File: app/components/auth.hbs [hunk 26]
```diff
@@ -0,0 +1,64 @@
...
+        {{on "submit" this.submitForm}}
+      >
+        {{#if this.isIpAddressStep}}
+          <Uc::Input
+            @label={{t "labels.ip_address"}}
+            @value={{this.ipAddress}}
+            @onInput={{this.handleIpAddress}}
+            @isError={{this.loginFailedMessage}}
+            @errorMessage={{this.loginFailedMessage}}
+            local-class="auth__input"
```
Comment (Turbo87) [inline app/components/auth.hbs:30]: why the `auth__` prefix if we're using a `local-class` anyway?

**Review by marcoow — APPROVED** [review]
Good job 🙌 

Let's just tidy up the commit history a bit – coincidentially @mansona just release his blog post on the topic ;) https://simplabs.com/blog/2021/05/26/keeping-a-clean-git-history/
